CREATE TABLE IF NOT EXISTS users(
	id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR(64) UNIQUE NOT NULL,
    `password` VARCHAR(256) NOT NULL,
    credit_card VARCHAR(16) NOT NULL,
    phone VARCHAR(16),
    rating DOUBLE NOT NULL DEFAULT 0.0,
    superuser TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS drivers(
	id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR(64) UNIQUE NOT NULL,
    `password` VARCHAR(256) NOT NULL,
    phone VARCHAR(16),
    rating DOUBLE NOT NULL DEFAULT 0.0,
    car VARCHAR(256) NOT NULL,
    license VARCHAR(16)
);

CREATE TABLE IF NOT EXISTS rides(
	id INT PRIMARY KEY AUTO_INCREMENT,
    customer VARCHAR(32) NOT NULL,
    driver VARCHAR(32) NOT NULL,
    ride_type VARCHAR(32) NOT NULL,
    `source` VARCHAR(256) NOT NULL,
    destination VARCHAR(256) NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    booked_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration DOUBLE NOT NULL DEFAULT 0.0,
    cancelled_on DATETIME DEFAULT NULL,
    cancel_reason VARCHAR(64) DEFAULT NULL,
    `distance` DOUBLE,
    price DOUBLE,
    zipcode VARCHAR(8),
    FOREIGN KEY(customer) REFERENCES USERS(username) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(driver) REFERENCES DRIVERS(username) ON UPDATE CASCADE ON DELETE CASCADE
);