POST http://127.0.0.1/rideshare/Login HTTP/1.1
content-type: application/json

{
    "username": "maneeshd",
    "password": "qwerty",
    "usertype": "customer"
} 

POST http://127.0.0.1/rideshare/Logout HTTP/1.1
content-type: application/json

{
    "username": "maneeshd",
    "token": "d7723cb3-5ff7-45de-9351-e81fa405d16f"
}

POST http://127.0.0.1/rideshare/Login HTTP/1.1
content-type: application/json

{
    "username": "maneeshd",
    "password": "qwerty545",
    "usertype": "customer"
}

POST http://127.0.0.1/rideshare/Login HTTP/1.1
content-type: application/json

{
    "username": "maneeshd",
    "password": "qwerty",
    "usertype": "admin"
}

POST http://127.0.0.1/rideshare/Login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "zxcvb",
    "usertype": "admin"
}

